// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhNxHzS2Ipw_-ghUPxXtZ2vKwvonWygo',
    appId: '1:915261357353:web:457b69bc4e5effc560cb38',
    messagingSenderId: '915261357353',
    projectId: 'nativeco-15409',
    authDomain: 'nativeco-15409.firebaseapp.com',
    storageBucket: 'nativeco-15409.appspot.com',
    measurementId: 'G-KLMZ3SP8ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvVqb714vBW_TT73ktb050_eD6-WCFOQ',
    appId: '1:915261357353:android:5021b4a1a7c1939260cb38',
    messagingSenderId: '915261357353',
    projectId: 'nativeco-15409',
    storageBucket: 'nativeco-15409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbohflAV59cTtrogcQTgH_kNbU33GbPY',
    appId: '1:915261357353:ios:23128f06f954ac1060cb38',
    messagingSenderId: '915261357353',
    projectId: 'nativeco-15409',
    storageBucket: 'nativeco-15409.appspot.com',
    iosClientId: '915261357353-k4jcc91cigblpopr0n9q5lm7cnj736va.apps.googleusercontent.com',
    iosBundleId: 'com.example.nativeco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbohflAV59cTtrogcQTgH_kNbU33GbPY',
    appId: '1:915261357353:ios:4c72780da3687f6160cb38',
    messagingSenderId: '915261357353',
    projectId: 'nativeco-15409',
    storageBucket: 'nativeco-15409.appspot.com',
    iosClientId: '915261357353-1q6k1f7cb21c6mm7mt01rrvhjojjjrt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nativeco.RunnerTests',
  );
}
